In [12]:
# Let's start by loading the train.csv file and taking a look at the data structure
import pandas as pd

train_df = pd.read_csv('train.csv')
train_df.head()

/var/folders/sb/2gzn9_qx589_ft0jp8q6nbbc0000gn/T/ipykernel_98946/2354593243.py:4: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  train_df = pd.read_csv('train.csv')

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
0,1,5,2015-07-31,5263,555,1,1,0,1
1,2,5,2015-07-31,6064,625,1,1,0,1
2,3,5,2015-07-31,8314,821,1,1,0,1
3,4,5,2015-07-31,13995,1498,1,1,0,1
4,5,5,2015-07-31,4822,559,1,1,0,1

In [13]:
# Let's load the store.csv file and take a look at the data structure
store_df = pd.read_csv('store.csv')
store_df.head()

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN

In [14]:
# Let's load the test.csv file and take a look at the data structure
test_df = pd.read_csv('test.csv')
test_df.head()

   Id  Store  DayOfWeek        Date  Open  Promo StateHoliday  SchoolHoliday
0   1      1          4  2015-09-17   1.0      1            0              0
1   2      3          4  2015-09-17   1.0      1            0              0
2   3      7          4  2015-09-17   1.0      1            0              0
3   4      8          4  2015-09-17   1.0      1            0              0
4   5      9          4  2015-09-17   1.0      1            0              0

In [15]:
# Merging the train and store dataframes
train_df = pd.merge(train_df, store_df, on='Store')

# Merging the test and store dataframes
test_df = pd.merge(test_df, store_df, on='Store')

train_df.head(), test_df.head()

(   Store  DayOfWeek        Date  Sales  Customers  Open  Promo StateHoliday  \
 0      1          5  2015-07-31   5263        555     1      1            0
 1      1          4  2015-07-30   5020        546     1      1            0
 2      1          3  2015-07-29   4782        523     1      1            0
 3      1          2  2015-07-28   5011        560     1      1            0
 4      1          1  2015-07-27   6102        612     1      1            0

    SchoolHoliday StoreType Assortment  CompetitionDistance  \
 0              1         c          a               1270.0
 1              1         c          a               1270.0
 2              1         c          a               1270.0
 3              1         c          a               1270.0
 4              1         c          a               1270.0

    CompetitionOpenSinceMonth  CompetitionOpenSinceYear  Promo2  \
 0                        9.0                    2008.0       0
 1                        9.0                    2008.0       0
 2                        9.0                    2008.0       0
 3                        9.0                    2008.0       0
 4                        9.0                    2008.0       0

    Promo2SinceWeek  Promo2SinceYear PromoInterval
 0              NaN              NaN           NaN
 1              NaN              NaN           NaN
 2              NaN              NaN           NaN
 3              NaN              NaN           NaN
 4              NaN              NaN           NaN  ,
      Id  Store  DayOfWeek        Date  Open  Promo StateHoliday  \
 0     1      1          4  2015-09-17   1.0      1            0
 1   857      1          3  2015-09-16   1.0      1            0
 2  1713      1          2  2015-09-15   1.0      1            0
 3  2569      1          1  2015-09-14   1.0      1            0
 4  3425      1          7  2015-09-13   0.0      0            0

    SchoolHoliday StoreType Assortment  CompetitionDistance  \
 0              0         c          a               1270.0
 1              0         c          a               1270.0
 2              0         c          a               1270.0
 3              0         c          a               1270.0
 4              0         c          a               1270.0

    CompetitionOpenSinceMonth  CompetitionOpenSinceYear  Promo2  \
 0                        9.0                    2008.0       0
 1                        9.0                    2008.0       0
 2                        9.0                    2008.0       0
 3                        9.0                    2008.0       0
 4                        9.0                    2008.0       0

    Promo2SinceWeek  Promo2SinceYear PromoInterval
 0              NaN              NaN           NaN
 1              NaN              NaN           NaN
 2              NaN              NaN           NaN
 3              NaN              NaN           NaN
 4              NaN              NaN           NaN  )

In [16]:
# Checking for missing values in the train and test dataframes
missing_values_train = train_df.isnull().sum()
missing_values_test = test_df.isnull().sum()

missing_values_train[missing_values_train > 0], missing_values_test[missing_values_test > 0]

(CompetitionDistance            2642
 CompetitionOpenSinceMonth    323348
 CompetitionOpenSinceYear     323348
 Promo2SinceWeek              508031
 Promo2SinceYear              508031
 PromoInterval                508031
 dtype: int64,
 Open                            11
 CompetitionDistance             96
 CompetitionOpenSinceMonth    15216
 CompetitionOpenSinceYear     15216
 Promo2SinceWeek              17232
 Promo2SinceYear              17232
 PromoInterval                17232
 dtype: int64)

In [17]:
# Filling missing values in both train and test data

# CompetitionDistance
train_df['CompetitionDistance'].fillna(train_df['CompetitionDistance'].median(), inplace=True)
test_df['CompetitionDistance'].fillna(test_df['CompetitionDistance'].median(), inplace=True)

# CompetitionOpenSinceMonth and CompetitionOpenSinceYear
train_df['CompetitionOpenSinceMonth'].fillna(0, inplace=True)
train_df['CompetitionOpenSinceYear'].fillna(0, inplace=True)
test_df['CompetitionOpenSinceMonth'].fillna(0, inplace=True)
test_df['CompetitionOpenSinceYear'].fillna(0, inplace=True)

# Promo2SinceWeek and Promo2SinceYear
train_df['Promo2SinceWeek'].fillna(0, inplace=True)
train_df['Promo2SinceYear'].fillna(0, inplace=True)
test_df['Promo2SinceWeek'].fillna(0, inplace=True)
test_df['Promo2SinceYear'].fillna(0, inplace=True)

# PromoInterval
train_df['PromoInterval'].fillna("No Promo", inplace=True)
test_df['PromoInterval'].fillna("No Promo", inplace=True)

# Open (in test data)
test_df['Open'].fillna(test_df['Open'].mode()[0], inplace=True)

train_df.isnull().sum(), test_df.isnull().sum()

(Store                        0
 DayOfWeek                    0
 Date                         0
 Sales                        0
 Customers                    0
 Open                         0
 Promo                        0
 StateHoliday                 0
 SchoolHoliday                0
 StoreType                    0
 Assortment                   0
 CompetitionDistance          0
 CompetitionOpenSinceMonth    0
 CompetitionOpenSinceYear     0
 Promo2                       0
 Promo2SinceWeek              0
 Promo2SinceYear              0
 PromoInterval                0
 dtype: int64,
 Id                           0
 Store                        0
 DayOfWeek                    0
 Date                         0
 Open                         0
 Promo                        0
 StateHoliday                 0
 SchoolHoliday                0
 StoreType                    0
 Assortment                   0
 CompetitionDistance          0
 CompetitionOpenSinceMonth    0
 CompetitionOpenSinceYear     0
 Promo2                       0
 Promo2SinceWeek              0
 Promo2SinceYear              0
 PromoInterval                0
 dtype: int64)

In [18]:
from sklearn.preprocessing import LabelEncoder

# Initiating the label encoder
le = LabelEncoder()


# Converting all values in the categorical columns to strings
categorical_cols = ['StateHoliday', 'StoreType', 'Assortment', 'PromoInterval']

for col in categorical_cols:
    train_df[col] = train_df[col].astype(str)
    test_df[col] = test_df[col].astype(str)

# Get unique values of StateHoliday, StoreType, Assortment, PromoInterval from both train and test datasets
state_holiday_all = pd.concat([train_df['StateHoliday'], test_df['StateHoliday']]).unique()
store_type_all = pd.concat([train_df['StoreType'], test_df['StoreType']]).unique()
assortment_all = pd.concat([train_df['Assortment'], test_df['Assortment']]).unique()
promo_interval_all = pd.concat([train_df['PromoInterval'], test_df['PromoInterval']]).unique()

# Fit LabelEncoder on all unique values
le.fit(state_holiday_all)
train_df['StateHoliday'] = le.transform(train_df['StateHoliday'])
test_df['StateHoliday'] = le.transform(test_df['StateHoliday'])

le.fit(store_type_all)
train_df['StoreType'] = le.transform(train_df['StoreType'])
test_df['StoreType'] = le.transform(test_df['StoreType'])

le.fit(assortment_all)
train_df['Assortment'] = le.transform(train_df['Assortment'])
test_df['Assortment'] = le.transform(test_df['Assortment'])

le.fit(promo_interval_all)
train_df['PromoInterval'] = le.transform(train_df['PromoInterval'])
test_df['PromoInterval'] = le.transform(test_df['PromoInterval'])

train_df.head(), test_df.head()

(   Store  DayOfWeek        Date  Sales  Customers  Open  Promo  StateHoliday  \
 0      1          5  2015-07-31   5263        555     1      1             0
 1      1          4  2015-07-30   5020        546     1      1             0
 2      1          3  2015-07-29   4782        523     1      1             0
 3      1          2  2015-07-28   5011        560     1      1             0
 4      1          1  2015-07-27   6102        612     1      1             0

    SchoolHoliday  StoreType  Assortment  CompetitionDistance  \
 0              1          2           0               1270.0
 1              1          2           0               1270.0
 2              1          2           0               1270.0
 3              1          2           0               1270.0
 4              1          2           0               1270.0

    CompetitionOpenSinceMonth  CompetitionOpenSinceYear  Promo2  \
 0                        9.0                    2008.0       0
 1                        9.0                    2008.0       0
 2                        9.0                    2008.0       0
 3                        9.0                    2008.0       0
 4                        9.0                    2008.0       0

    Promo2SinceWeek  Promo2SinceYear  PromoInterval
 0              0.0              0.0              3
 1              0.0              0.0              3
 2              0.0              0.0              3
 3              0.0              0.0              3
 4              0.0              0.0              3  ,
      Id  Store  DayOfWeek        Date  Open  Promo  StateHoliday  \
 0     1      1          4  2015-09-17   1.0      1             0
 1   857      1          3  2015-09-16   1.0      1             0
 2  1713      1          2  2015-09-15   1.0      1             0
 3  2569      1          1  2015-09-14   1.0      1             0
 4  3425      1          7  2015-09-13   0.0      0             0

    SchoolHoliday  StoreType  Assortment  CompetitionDistance  \
 0              0          2           0               1270.0
 1              0          2           0               1270.0
 2              0          2           0               1270.0
 3              0          2           0               1270.0
 4              0          2           0               1270.0

    CompetitionOpenSinceMonth  CompetitionOpenSinceYear  Promo2  \
 0                        9.0                    2008.0       0
 1                        9.0                    2008.0       0
 2                        9.0                    2008.0       0
 3                        9.0                    2008.0       0
 4                        9.0                    2008.0       0

    Promo2SinceWeek  Promo2SinceYear  PromoInterval
 0              0.0              0.0              3
 1              0.0              0.0              3
 2              0.0              0.0              3
 3              0.0              0.0              3
 4              0.0              0.0              3  )

In [19]:
from sklearn.preprocessing import MinMaxScaler

# Initiating the MinMaxScaler
scaler = MinMaxScaler()

# List of numerical columns to be normalized
numerical_cols = ['CompetitionDistance', 'CompetitionOpenSinceMonth', 'CompetitionOpenSinceYear', 
                  'Promo2SinceWeek', 'Promo2SinceYear', 'Sales', 'Customers']

# Fit the scaler on the train data and transform both train and test data
train_df[numerical_cols] = scaler.fit_transform(train_df[numerical_cols])
# We drop Sales and Customers columns from the test set because they don't exist in the test set
test_df[numerical_cols[:-2]] = scaler.transform(test_df[numerical_cols[:-2]])

train_df.head(), test_df.head()

ValueError: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Customers
- Sales